version: 2
jobs:
  build:
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-go

    docker:
      - image: circleci/golang:1.9

    steps:
      - checkout

      - run: ssh-keyscan ${KIBANA_HOST} >> ~/.ssh/known_hosts

      - setup_remote_docker:
        docker_layer_caching: true

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
        name: "Make"
        command: |
          make build-collector-linux

      - save_cache:
        key: v1-pkg-cache
        paths:
          - "/go/pkg"

      - run:
        name: "Build image"
        command: |
          docker login $DOCKER_USERNAME $DOCKERHUB_PASSWORD
          docker build -t dashbase/jaeger-collector:develop ./cmd/collector
          docker push dashbase/jaeger-collector:develop


workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
